### ISSUE TITLE
CI focused testing based on compiler commit

### ISSUE THREAD

**Issue by jmid** [ocaml-multicore/multicoretests#286]
I just tried the CI options to test a compiler based on a specific commit `'7942816c0'`
This failed because after downloading the directory is named with the full hash: `ocaml- 7942816c058b0ad2ca168e9f4063eaaa8240ba79/` - see e.g. https://github.com/ocaml-multicore/multicoretests/actions/runs/3968857974/jobs/6802577780

I then switched to specifying a full git hash in c6c16d6 - which fails since it didn't pin the 5.1-version of `ppxlib`
https://github.com/ocaml-multicore/multicoretests/actions/runs/3968925696/jobs/6802734116

None of this was unsolvable - but I'm likely to forget again and hence writing it here to remind my future self :sweat_smile: 

For the future, we could
- document in the `common.yml` workflow file that full hashes are expected
- `pin` the 5.1-version of `ppxlib` for the commit-based testing as we are probably most likely to do so on 5.1 commits (and the 5.1 ppxlib version is backwards compatible)

@shym What do you think? :thinking:

**Comment by shym** [comment]
Indeed, we could document the fact that this variable must be the full hash (it could also be tag, but I’m not sure we’ve ever used this).
As for `ppxlib`, the more recent CI configuration should work :crossed_fingers: as they always set up the repository containing the 5.1-only version of `ppxlib`.
(I was wondering if that step should be rewritten, and how, in particular so that it’s compatible with windows runs, which also means behaving nicely to an older opam)

**Comment by shym** [comment]
The PR I propose to close this issue would render unnecessary the full hashes. But it leaves the question that the explanations on the meaning of each variable is given in the description of the input and the common usage we have developed is to directly set the value of the environment variable, so bypassing the `inputs`.
I still find this good enough, thinking that they could be put to interesting uses as `inputs`.
